#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#
global:
  fullnameOverride: echo

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 31
          pullPolicy: IfNotPresent

        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false

ingress:
  main:
    enabled: false
    # hosts:
    #   - host: "test.local"
    #     paths:
    #       - path: /
    #         service:
    #           identifier: main
    #           port: http
    # tls:
    #   - hosts:
    #       - "test.local"

service:
  main:
    enabled: false

persistence:
  config:
    enabled: false
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    storageClass: longhorn
    size: 1Gi
    globalMounts:
      - path: /config